version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: onealbania/api:${TAG:-latest}
    container_name: onealbania-api
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    env_file:
      - ./api/.env
    depends_on:
      - db
    networks:
      - onealbania-network
    volumes:
      - api-logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: mysql:8.0
    container_name: onealbania-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-one_albania_db}
      MYSQL_USER: ${DB_USER:-onealbania}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./api/scripts/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - onealbania-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  monitoring:
    image: prom/prometheus:latest
    container_name: onealbania-monitoring
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - onealbania-network
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: onealbania-grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - onealbania-network
    depends_on:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: onealbania-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - onealbania-network

networks:
  onealbania-network:
    driver: bridge

volumes:
  api-logs:
  db-data:
  prometheus-data:
  grafana-data:
